#credit to Aaron Lerch on helping me figure out how you can keep the real functions around

rename-item function:Chocolatey-Help Chocolatey-Help-Actual
rename-item function:Chocolatey-Install Chocolatey-Install-Actual
rename-item function:Chocolatey-InstallAll Chocolatey-InstallAll-Actual
rename-item function:Chocolatey-InstallIfMissing Chocolatey-InstallIfMissing-Actual
rename-item function:Chocolatey-List Chocolatey-List-Actual
rename-item function:Chocolatey-Nuget Chocolatey-Nuget-Actual
rename-item function:Chocolatey-Pack Chocolatey-Pack-Actual
rename-item function:Chocolatey-PackagesConfig Chocolatey-PackagesConfig-Actual
rename-item function:Chocolatey-Push Chocolatey-Push-Actual
rename-item function:Chocolatey-RubyGem Chocolatey-RubyGem-Actual
rename-item function:Chocolatey-Update Chocolatey-Update-Actual
rename-item function:Chocolatey-Version Chocolatey-Version-Actual
rename-item function:Chocolatey-WebPI Chocolatey-WebPI-Actual
rename-item function:Chocolatey-Cygwin Chocolatey-Cygwin-Actual
rename-item function:Delete-ExistingErrorLog Delete-ExistingErrorLog-Actual
rename-item function:Generate-BinFile Generate-BinFile-Actual
rename-item function:Get-ChocolateyBins Get-ChocolateyBins-Actual
rename-item function:Get-ConfigValue Get-ConfigValue-Actual
rename-item function:Get-LatestPackageVersion Get-LatestPackageVersion-Actual
rename-item function:Get-LongPackageVersion Get-LongPackageVersion-Actual
rename-item function:Get-PackageFolderVersions Get-PackageFolderVersions-Actual
rename-item function:Get-PackageFoldersForPackage Get-PackageFoldersForPackage-Actual
rename-item function:Get-VersionsForComparison Get-VersionsForComparison-Actual
rename-item function:Remove-LastInstallLog Remove-LastInstallLog-Actual
rename-item function:Run-ChocolateyPS1 Run-ChocolateyPS1-Actual
rename-item function:Run-ChocolateyProcess Run-ChocolateyProcess-Actual
rename-item function:Run-NuGet Run-NuGet-Actual

rename-item function:Get-ChocolateyUnzip Get-ChocolateyUnzip-Actual
rename-item function:Get-ChocolateyWebFile Get-ChocolateyWebFile-Actual
#rename-item function:Get-WebFile Get-WebFile-Actual
rename-item function:Install-ChocolateyDesktopLink Install-ChocolateyDesktopLink-Actual
rename-item function:Install-ChocolateyInstallPackage Install-ChocolateyInstallPackage-Actual
rename-item function:Install-ChocolateyPackage Install-ChocolateyPackage-Actual
rename-item function:Install-ChocolateyPath Install-ChocolateyPath-Actual
rename-item function:Install-ChocolateyPowershellCommand Install-ChocolateyPowershellCommand-Actual
rename-item function:Install-ChocolateyZipPackage Install-ChocolateyZipPackage-Actual
rename-item function:Start-ChocolateyProcessAsAdmin Start-ChocolateyProcessAsAdmin-Actual
rename-item function:Write-ChocolateyFailure Write-ChocolateyFailure-Actual
rename-item function:Write-ChocolateySuccess Write-ChocolateySuccess-Actual