using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("Fervent Coder Software")]
[assembly: AssemblyVersionAttribute("0.9.8.1")]
[assembly: AssemblyFileVersionAttribute("0.9.8.0")]
[assembly: AssemblyInformationalVersionAttribute("0.9.8.b5fd7dbf5fc1548fca702a69abad87e7d61adce4")]
[assembly: AssemblyTitleAttribute("chocolatey")]
[assembly: AssemblyProductAttribute("chocolatey")]
[assembly: AssemblyDescriptionAttribute("chocolatey is like apt-get, but for windows.")]
[assembly: AssemblyTrademarkAttribute("chocolatey - Fervent Coder Software")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2011 Fervent Coder Software, - Original author or authors")]

